INSERT INTO
  tb_provinsi (nama_provinsi)
VALUES
  ('Aceh'),
  ('Sumatera Utara'),
  ('Sumatera Barat'),
  ('Riau'),
  ('Jambi'),
  ('Sumatera Selatan'),
  ('Bengkulu'),
  ('Lampung'),
  ('Bangka Belitung'),
  ('Kepulauan Riau'),
  ('DKI Jakarta'),
  ('Jawa Barat'),
  ('Jawa Tengah'),
  ('Jawa Timur'),
  ('Banten'),
  ('Bali'),
  ('Nusa Tenggara Barat'),
  ('Nusa Tenggara Timur'),
  ('Kalimantan Barat'),
  ('Kalimantan Tengah'),
  ('Kalimantan Selatan'),
  ('Kalimantan Timur'),
  ('Kalimantan Utara'),
  ('Sulawesi Utara'),
  ('Sulawesi Tengah'),
  ('Sulawesi Selatan'),
  ('Sulawesi Tenggara'),
  ('Gorontalo'),
  ('Maluku'),
  ('Maluku Utara'),
  ('Papua'),
  ('Papua Barat');