-- Data untuk Provinsi Bali (id_provinsi = 16)
INSERT INTO
  tb_kabupaten (id_provinsi, nama_kabupaten)
VALUES
  (16, 'Badung'),
  (16, 'Bangli'),
  (16, 'Buleleng'),
  (16, 'Gianyar'),
  (16, 'Jembrana'),
  (16, 'Karangasem'),
  (16, 'Klungkung'),
  (16, 'Tabanan'),
  (1, 'Aceh Barat'),
  (1, 'Aceh Barat Daya'),
  (1, 'Aceh Besar'),
  (1, 'Aceh Jaya'),
  (1, 'Aceh Selatan'),
  (1, 'Aceh Singkil'),
  (1, 'Aceh Tamiang'),
  (1, 'Aceh Tengah'),
  (1, 'Aceh Tenggara'),
  (1, 'Aceh Timur'),
  (1, 'Aceh Utara'),
  (1, 'Bener Meriah'),
  (1, 'Bireuen'),
  (1, 'Gayo Lues'),
  (1, 'Langsa'),
  (1, 'Lhokseumawe'),
  (1, 'Nagan Raya'),
  (1, 'Pidie'),
  (1, 'Pidie Jaya'),
  (1, 'Sabang'),
  (1, 'Simeulue'),
  (1, 'Subulussalam'),
  (2, 'Asahan'),
  (2, 'Batu Bara'),
  (2, 'Binjai'),
  (2, 'Dairi'),
  (2, 'Deli Serdang'),
  (2, 'Gunungsitoli'),
  (2, 'Humbang Hasundutan'),
  (2, 'Karo'),
  (2, 'Labuhan Batu'),
  (2, 'Labuhan Batu Selatan'),
  (2, 'Labuhan Batu Utara'),
  (2, 'Langkat'),
  (2, 'Mandailing Natal'),
  (2, 'Medan'),
  (2, 'Nias'),
  (2, 'Nias Barat'),
  (2, 'Nias Selatan'),
  (2, 'Nias Utara'),
  (2, 'Padang Lawas'),
  (2, 'Padang Lawas Utara'),
  (2, 'Pakpak Bharat'),
  (2, 'Pematang Siantar'),
  (2, 'Samosir'),
  (2, 'Sibolga'),
  (2, 'Simalungun'),
  (2, 'Tanjung Balai'),
  (2, 'Tapanuli Selatan'),
  (2, 'Tapanuli Tengah'),
  (2, 'Tapanuli Utara'),
  (2, 'Tebing Tinggi'),
  (3, 'Agam'),
  (3, 'Dharmasraya'),
  (3, 'Kepulauan Mentawai'),
  (3, 'Lima Puluh Kota'),
  (3, 'Padang'),
  (3, 'Padang Panjang'),
  (3, 'Pariaman'),
  (3, 'Pasaman'),
  (3, 'Pasaman Barat'),
  (3, 'Payakumbuh'),
  (3, 'Sawahlunto'),
  (3, 'Solok'),
  (3, 'Solok Selatan'),
  (3, 'Tanah Datar'),
  (4, 'Bengkalis'),
  (4, 'Indragiri Hilir'),
  (4, 'Indragiri Hulu'),
  (4, 'Kampar'),
  (4, 'Kepulauan Meranti'),
  (4, 'Pelalawan'),
  (4, 'Rokan Hilir'),
  (4, 'Rokan Hulu'),
  (4, 'Siak'),
  (5, 'Bungo'),
  (5, 'Jambi'),
  (5, 'Kerinci'),
  (5, 'Merangin'),
  (5, 'Muaro Jambi'),
  (5, 'Sarolangun'),
  (5, 'Tanjung Jabung Barat'),
  (5, 'Tanjung Jabung Timur'),
  (5, 'Tebo'),
  (6, 'Ogan Komering Ulu'),
  (6, 'Ogan Komering Ilir'),
  (6, 'Muara Enim'),
  (6, 'Lahat'),
  (6, 'Musi Rawas'),
  (6, 'Musi Banyuasin'),
  (6, 'Banyuasin'),
  (6, 'Ogan Komering Ulu Selatan'),
  (6, 'Ogan Komering Ulu Timur'),
  (6, 'Ogan Ilir'),
  (6, 'Empat Lawang'),
  (6, 'Penukal Abab Lematang Ilir'),
  (6, 'Musi Rawas Utara'),
  (6, 'Musi Rawas Timur'),
  (6, 'Musi Banyuasin'),
  (6, 'Musi Banyuasin Timur'),
  (6, 'Banyuasin'),
  (6, 'Banyuasin Timur'),
  (6, 'Banyuasin Selatan'),
  (6, 'Banyuasin Tengah'),
  (6, 'Ogan Komering Ulu Selatan'),
  (6, 'Ogan Komering Ulu Timur'),
  (6, 'Ogan Ilir'),
  (6, 'Ogan Komering Ulu Selatan'),
  (6, 'Ogan Komering Ulu Timur'),
  (7, 'Bengkulu Selatan'),
  (7, 'Bengkulu Tengah'),
  (7, 'Bengkulu Utara'),
  (7, 'Kaur'),
  (7, 'Kepahiang'),
  (7, 'Lebong'),
  (7, 'Muko-Muko'),
  (7, 'Rejang Lebong'),
  (7, 'Seluma'),
  (8, 'Bandar Lampung'),
  (8, 'Lampung Barat'),
  (8, 'Lampung Selatan'),
  (8, 'Lampung Tengah'),
  (8, 'Lampung Timur'),
  (8, 'Lampung Utara'),
  (8, 'Mesuji'),
  (8, 'Pesawaran'),
  (8, 'Pesisir Barat'),
  (8, 'Pringsewu'),
  (8, 'Tanggamus'),
  (8, 'Tulang Bawang'),
  (8, 'Tulang Bawang Barat'),
  (8, 'Way Kanan'),
  (9, 'Bangka'),
  (9, 'Bangka Barat'),
  (9, 'Bangka Selatan'),
  (9, 'Bangka Tengah'),
  (9, 'Belitung'),
  (9, 'Belitung Timur'),
  (9, 'Pangkal Pinang'),
  (10, 'Kabupaten Bintan'),
  (10, 'Kabupaten Karimun'),
  (10, 'Kabupaten Lingga'),
  (10, 'Kabupaten Natuna'),
  (10, 'Kota Batam'),
  (10, 'Kota Tanjung Pinang');